ARG HA_VERSION
FROM haproxy:${HA_VERSION}

RUN mkdir /var/lib/haproxy/
RUN apt-get update && apt-get install -y bc certbot

COPY ./le-renew-haproxy /usr/local/sbin/le-renew-haproxy
RUN chmod +x /usr/local/sbin/le-renew-haproxy
COPY ./haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
